### ISSUE TITLE
Linking issue on electron 1.5+ on Linux

### ISSUE THREAD

**Issue by Kagami** [Kagami/mpv.js#10]
https://github.com/electron/libchromiumcontent/issues/268
https://bugs.chromium.org/p/chromium/issues/detail?id=52105
https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/M4U8oFpMSSc/aYF187J-S8QJ

**Comment by Kagami** [comment]
Made it!

```
nm -D electron | awk '/ \w (av|ff)/{print $3}' | xargs rebind -w -i electron
```

With that patch to [rebind](https://github.com/BR903/ELFkickers):

```patch
diff --git a/rebind/rebind.c b/rebind/rebind.c
index 16252ad..dd16cae 100644
--- a/rebind/rebind.c
+++ b/rebind/rebind.c
@@ -151,7 +151,8 @@ static int changesymbols(Elf64_Sym *symtab, char const *strtab, int count)
 	name = strtab + sym->st_name;
 	if (!bsearch(&name, namelist, namecount, sizeof *namelist, qstrcmp))
 	    continue;
-	if (chgbind) {
+	sym->st_info = 0;
+	if (0) {
 	    if (ELF64_ST_BIND(sym->st_info) == STB_LOCAL) {
 		fprintf(stderr, "warning: cannot rebind local symbol \"%s\"\n",
 				name);
@@ -159,7 +160,7 @@ static int changesymbols(Elf64_Sym *symtab, char const *strtab, int count)
 	    }
 	    sym->st_info = ELF64_ST_INFO(tobind, ELF64_ST_TYPE(sym->st_info));
 	}
-	if (chgvisibility)
+	if (0)
 	    sym->st_other = ELF64_ST_VISIBILITY(tovisibility);
 	if (verbose)
 	    printf("%s: \"%s\" altered.\n", thefilename, name);
```

So crazy but works.

**Comment by williamoliveira** [comment]
Is this workaround still necessary?

**Comment by Kagami** [comment]
It's fixed in latest versions of Electron (restored explicit dependency on libffmpeg).
I like the previous behavior a bit more though, because you don't have to depend on shared ffmpeg libraries with specific version (major number) on target user system.

(Actually it's possible to remove libffmpeg dependency even in latest versions, but it's even more crazy, you need to patch binary for that.)
