### ISSUE TITLE
v47 prebuilds

### ISSUE THREAD

**Issue by antidiestro** [Kagami/mpv.js#11]
when trying to build my application, it looks for releases in the repo marked for v47, but it only finds for v42. any other way of solving it apart from building my own?

**Comment by Kagami** [comment]
You need to specify `-t 1.0.0` flag for prebuild-install. It's just single hardcoded version because Pepper ABI doesn't actually depend on V8 or Electron versions.

**Comment by antidiestro** [comment]
@Kagami I am dumb as fuck. Could you give me a hand through the whole packaging process? I'm on Mac and I'm not sure what to do with the `mpvjs.node` and `dylib` files. I just want to package this for Mac for the time being. I'm using `electron-builder`.
