### ISSUE TITLE
Plugin could not be loaded error

### ISSUE THREAD

**Issue by LukasBombach** [Kagami/mpv.js#12]
Hello, I am trying to get this awesome, awesome project to work in my electron app. However, I am struggling with getting it to run. I put  the code from 

> Load plugin in main process (Electron example)

[of your readme](https://github.com/Kagami/mpv.js#load-plugin-in-main-process-electron-example) to the `electron-starter.js` file that the electron quick start app generates, e.g. the file that boots up electron and creates a window. [Here is a full gist of that file](https://gist.github.com/LukasBombach/02a5e0d1b918d4a41c76c2917d04a67f). However, all I see is an error saying that the plugin could not be loaded. 

Can you help?

**Comment by Kagami** [comment]
Code looks ok. What version of Electron do you use and what's your OS? Can you show screenshot of the error?

**Comment by Kagami** [comment]
Ugh, just realized, I forgot to mention one important thing in the readme. Please add `plugins: true` option to the `webPreferences` and try again.

**Comment by LukasBombach** [comment]
Hi, thanks for answering! There is actually 2 things that happened! First of all: you were right about the `webPreferences`! But second of all I actually ran 2 projects, one react app with a dev sever and a separate one starting electron. And I added `mpv.js` to the wrong project! Now everything works! Thanks so much for this awesome project, I have been waiting so long for this because I always wanted to code a media center based on react!

One thing to note if you update your readme, you also have a dependency to `react`, you may want to tell them to `npm i mpv.js react`.

Again, thank you very much!
