### ISSUE TITLE
Set mpv options (e.g. --loop-file=inf)?

### ISSUE THREAD

**Issue by simpleshadow** [Kagami/mpv.js#13]
How do you set the `--loop-file` option to `inf`? 
 
It would seem this is not a property. Attempting to set it as a property causes the Electron app to crash. I've tried sending it as a command as well to no avail. I think you need to set this option prior to the embed but I'm not certain if there's a way to do that with mpv.js?

Thanks.

(P.S. This is an amazing library. I've currently got it running in an Ember powered Electron app.)

**Comment by Kagami** [comment]
```patch
diff --git a/example/renderer.js b/example/renderer.js
index 9c93ff2..a932c75 100644
--- a/example/renderer.js
+++ b/example/renderer.js
@@ -38,6 +38,7 @@ class Main extends React.PureComponent {
   }
   handleMPVReady(mpv) {
     this.mpv = mpv;
+    this.mpv.property("loop-file", true);
     const observe = mpv.observe.bind(mpv);
     ["pause", "time-pos", "duration", "eof-reached"].forEach(observe);
     this.mpv.command("loadfile", path.join(__dirname, "tos.mkv"));
```

This works for me.

**Comment by simpleshadow** [comment]
@Kagami Works for me too 👍 :
```javascript
$('embed')[0].postMessage({"type": "set_property", "data": {"name": "loop-file", "value": true }});
```

Why does this work when set `true`? MPV docs indicate it's an option `--loop-file=<N|inf|no>`.

**Comment by Kagami** [comment]
set_property uses `mpv_set_property` so it needs correct value type (which is autodetected in HandleMessage in index.cc). We can introduce set_property_string message which will use `mpv_set_property_string` instead if needed.

**Comment by simpleshadow** [comment]
@Kagami I think the `mpv_set_property_string` would be very useful and unsure how to go about it. 

I'm currently trying to figure out how to issue the following command via `mpv.js` to create temporary thumbnail images:
```
mpv --really-quiet --vo=image --vo-image-format=jpg --aid=no --sid=no --start=1% --frames=1 video.avi
```

I'm assuming it is not possible without a `mpv_set_property_string`?

EDIT:

Currently trying to post the following set of messages causes Electron to crash:
```javascript
var embed = $('embed')[0];
embed.postMessage({"type": "set_property", "data": {"name": "really-quiet", "value": null }});
embed.postMessage({"type": "set_property", "data": {"name": "frames", "value": 1 }});
embed.postMessage({"type": "set_property", "data": {"name": "vo", "value": "image" }});
embed.postMessage({"type": "set_property", "data": {"name": "vo-image-format", "value": "jpg" }});
embed.postMessage({"type": "set_property", "data": {"name": "aid", "value": "no" }});
embed.postMessage({"type": "set_property", "data": {"name": "sid", "value": "no" }});
embed.postMessage({"type": "set_property", "data": {"name": "start", "value": "1%" }});
embed.postMessage({"type": "command", "data": ["loadfile", "video.avi", "replace"]});
```

**Comment by Kagami** [comment]
You shouldn't use mpv.js for creating thumbnails, it's a video player library.
