### ISSUE TITLE
Deploying the application

### ISSUE THREAD

**Issue by yugosonegi** [Kagami/mpv.js#19]
I was wondering how would I deploy the application. On the example it says that I have to have the dlls inside the system32 on windows folder and on linux it should be installed, I tried to put the dll inside the project folder and it doesn't load, is this right or there's a way to deploy everything together?

**Comment by Kagami** [comment]
You need to copy mpv-1.dll to the directory with mpvjs.node

**Comment by yugosonegi** [comment]
Sorry for my ignorance but what you mean?

**Comment by yugosonegi** [comment]
?

**Comment by Kagami** [comment]
See https://github.com/Kagami/mpv.js#windows
`mpv-1.dll` is name of the file from lachs0r builds.
