### ISSUE TITLE
Support for mpv 0.28.0

### ISSUE THREAD

**Issue by romaincointepas** [Kagami/mpv.js#23]
Hi, any plans to support the latest mpv version? (released Dec 25th)

Something seems to be broken at the moment.

**Comment by Kagami** [comment]
Yea, I've got some report seems to be related to latest mpv - https://github.com/Kagami/boram/issues/26
Need to check it.

**Comment by romaincointepas** [comment]
The latest version on homebrew is the 0.27.0 at the moment though. When trying the 0.28.0 (by simply modifying the formula and fetching the 0.28.0), the component doesn't even want to load.

**Comment by Kagami** [comment]
I've just run

```bash
git clone https://github.com/Kagami/mpv.js.git && cd mpv.js
npm install
npm run example
```

on macOS 12.10.6 with mpv 0.29.0. Works fine for me.

Please comment if you still can reproduce the issue.
