### ISSUE TITLE
mpv crashes when loading custom scripts

### ISSUE THREAD

**Issue by itshaadi** [Kagami/mpv.js#24]
I followed the documentation on [lua scripting](https://mpv.io/manual/master/#lua-scripting) and since [options](https://mpv.io/manual/master/#options) can be set as runtime via properties as well the following line should load my custom script
```
this.mpv.property('script', path.join(__dirname, 'mpv_commons.lua'))
```
but instead it just crashed

os: windows 10_x64 build 16299
electron: 1.8.4

**screenshots**

<img src="https://user-images.githubusercontent.com/10201704/39329880-f57efa76-49b4-11e8-8b66-4010410d9045.png" width="300" height="150">

<img src="https://user-images.githubusercontent.com/10201704/39329888-fc6fe0d4-49b4-11e8-9f79-5a72078253e7.png" width="500" height="300">

**Comment by itshaadi** [comment]
using command interface to change the property doesn't crash MPV so it might load the script.
``` 
this.mpv.command('set script', path.join(__dirname, 'mpv_commons.lua'))
```

so I used [this script](https://github.com/yuukidach/mpv-scripts/blob/master/show_filename.lua) as an example but it doesn't work. this could be because of mpv build wasn't compiled with lua support. but I doubt that since i'm using [mpv-dev](https://mpv.srsfckn.biz/mpv-dev-latest.7z). is there a way to find out if this command failed?

**Comment by Kagami** [comment]
Try with `MPVJS_TERMINAL=1 MPVJS_VERBOSE=1` environment variables.

**Comment by itshaadi** [comment]
OK so `set script` is not a command. and also for `this.mpv.property('script')` says `Do not use script, use scripts, bug reports will be ignored.`  but `scripts` is not a property. then I tried to force a different configuration directory.
```js
this.mpv.property('config-dir', path.join(__dirname, 'mpv', 'config'))
```
so that mpv would load the scripts inside `__dirname/mpv/config/scripts`.  but this time crashed with no specific reason.

[this line](https://gist.github.com/itshaadi/058f1178b34b48321c363579aa061a2e#file-mpv-log-L43) in the log file indicates the following situation:

```js
  handleMPVReady (mpv) {
    this.mpv = mpv
    const observe = mpv.observe.bind(mpv);
    ['pause', 'time-pos', 'duration', 'eof-reached', 'volume', 'mute'].forEach(observe)
    this.mpv.property('volume', this.state.volume)
    this.mpv.property('mute', this.state.mute)
    this.mpv.property('config-dir', path.join(__dirname, 'mpv', 'config')) //crash no info
  }
```

**Comment by Kagami** [comment]
Seems like it crashes because of:

```
[opengl-cb/cuda-nvdec] need OpenGL >= 2.1 or OpenGL-ES >= 3.0
[opengl-cb] Loading failed.
```

Not because of Lua script. Does it play some test files for you without Lua script?

**Comment by Kagami** [comment]
It seems to be related only to hwdec though.

**Comment by itshaadi** [comment]
yes I have no problem with playing files without Lua script.

**Comment by itshaadi** [comment]
in IRC someone mentioned that `--script` is a CLI method that appends to the --scripts option. and since `--scripts` isn't a property I'm guessing that it is not exposed to libmpv.

though this quote from IRC says it is possible
```quote
<CounterPillow> you can set the "scripts" property, as far as I understand
```
and as for `config-dir`. it is also a CLI option and it is mentioned that most options can be set as runtime via properties as well. but this one isn't. and properties in general might have very different behavior from the options.

I'm leaving this open for you to decide. see if it is possible to set the scripts property on your end.

**Comment by itshaadi** [comment]
turned out [load-script](https://mpv.io/manual/master/#input-commands-that-are-possibly-subject-to-change) will do the trick but it is listed as "Possibly Subject to Change". I tried it with [seek-show-position.js](seek-show-position.js)
```javascript
this.mpv.command('load-script', path.join(__dirname, 'seek-show-position.js'))
```

**Comment by Kagami** [comment]
Crash was actually caused by a bug of handling string properties, see #31. Your first example should work now.
