### ISSUE TITLE
not able to apply video filter

### ISSUE THREAD

**Issue by EdwardLiao** [Kagami/mpv.js#31]
Hi Kagami, 

I'm try to using video filter with mpv.js. It works for command line version of mpv:

'''
 mpv THE_BRIDGE.avi --vf=lavfi=[gradfun=20:30,vflip]
'''
The video will be flipped while playing.

I tried to do the same thing from mpv.js, by using reactmpv's  property method:

'''
 this.mpv.property('vf', "lavfi=[gradfun=20:30,vflip]");
'''

But the mpv.js just stopped work, and nothing else happened.

Could you please let me know the correct way to do it? Thanks.

Edward.

**Comment by Kagami** [comment]
Hi.

Plese enable `MPVJS_TERMINAL=1` and `MPVJS_VERBOSE=1` environment variables and show the output on the terminal.

**Comment by EdwardLiao** [comment]
Hi Kagami,

I added the env variables, and found mpv start to output things like these:

AV: 00:58:58 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:58 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:58 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:58 / 02:17:20 (42%) A-V: -0.000
AV: 00:58:58 / 02:17:20 (42%) A-V: -0.000
AV: 00:58:58 / 02:17:20 (42%) A-V: -0.000
AV: 00:58:58 / 02:17:20 (42%) A-V: -0.000
AV: 00:58:59 / 02:17:20 (42%) A-V: -0.000
AV: 00:58:59 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:59 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:59 / 02:17:20 (42%) A-V: -0.000
AV: 00:58:59 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:59 / 02:17:20 (42%) A-V:  0.000
AV: 00:58:59 / 02:17:20 (42%) A-V:  0.000

And after I added the filter, mpv stopped working, and nothing is found in the terminal.

**Comment by Kagami** [comment]
Can you add filter right in the onready handler? I.e. don't start the playback.

**Comment by EdwardLiao** [comment]
I added the filer inside onready handler (without playback), but got nothing from terminal.

**Comment by EdwardLiao** [comment]
I'm using Electron 2.0.3 on macOS 10.13.5, btw.

**Comment by Kagami** [comment]
I can reproduce it on Linux too. Just after setting `vf=flip`. Will try to reproduce with official libmpv examples.

**Comment by EdwardLiao** [comment]
Thanks!

**Comment by Kagami** [comment]
Found it. All string properties segfault because it should be pointer to c_str and I pass just c_str.
Seems like it was broken from the beginning so thanks for report.

I will release fixed version soon.

**Comment by Kagami** [comment]
Please try 0.3.0.

**Comment by EdwardLiao** [comment]
Cool!

**Comment by EdwardLiao** [comment]
It works for me, thank you for your timely support!
