### ISSUE TITLE
How to play m3u8 File?

### ISSUE THREAD

**Issue by lixiaojian** [Kagami/mpv.js#35]
hello How to play m3u8 File?

**Comment by Kagami** [comment]
Show contents of your m3u8.

I suppose you need to:

```js
this.mpv.property("demuxer-lavf-o", "protocol_whitelist=[file,tcp,tls,http,https]");
```

if you're trying to open local m3u8 file with http/https links. It's disabled by default for security reasons.

See https://github.com/mpv-player/mpv/issues/2937 https://github.com/mpv-player/mpv/issues/4488

**Comment by lixiaojian** [comment]
@Kagami  Thank you, it's work!
