### ISSUE TITLE
use Electron2 has a error  "[.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexImage2D: invalid internal_format GL_RGBA16_EXT"

### ISSUE THREAD

**Issue by lixiaojian** [Kagami/mpv.js#36]
hello , use Electron2 has a error  "[.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexImage2D: invalid internal_format GL_RGBA16_EXT".  use Electron1 it's  doesn't  has  this error.  (on windows)

**Comment by Kagami** [comment]
Duplicates #25
It should be safe to ignore, see https://github.com/Kagami/mpv.js/issues/25#issuecomment-406833585
