### ISSUE TITLE
"loadfile" command with additional arguments

### ISSUE THREAD

**Issue by emilhakobian** [Kagami/mpv.js#37]
I'm trying to call a "loadfile" command with additional arguments. Like : 
this.mpv.command('loadfile', 'file://' + PATH_TO_FILE, 'replace', ["--start=0", "--end=10"])

In this case video is not loading at all. Can you help ?

**Comment by Kagami** [comment]
Use

```
this.mpv.property("start", "0");
this.mpv.property("end", "10");
```

**Comment by emilhakobian** [comment]
Thanks this is also working like this: 
this.mpv.command('loadfile', 'file://' + PATH_TO_FILE, 'replace', ["start=0", "end=10"])
