### ISSUE TITLE
Is there a way to debug compatible issue?

### ISSUE THREAD

**Issue by EdwardLiao** [Kagami/mpv.js#41]
Hi Kagami,

I'm working on a video player for macOS, which use mpv.js as its video playback engine.

Most of the users use this player just fine, everything works perfectly.

But some of them complained that they can not play any mkv files. The video player displayed a green screen only (audio is ok).

I'm not quite clear about what happened.  Is there anyway to get some useful debug info from mpv.js?

BTW,  I suspected it is related to hardware decoding. But the default settings of hardware decoding is off (hwdec=no). So this is probably a dead end.

I also tried to set another value for vo, but from the doc of mpv.io, I can not find a reasonable value to replace the default "gpu" one.

So now I'm blocked by this problem, any suggestion is highly welcome, thanks!

**Comment by Kagami** [comment]
It might be related to video card, graphics drivers and OpenGL implementation.
mpv.js requires working OpenGL to play files.

Best way to start is to ask users with such problem show screenshot of the `chrome://gpu` page in Chrome. It should say that Canvas/WebGL are hardware accelerated.

**Comment by circleapps** [comment]
Thanks for letting me know this method,  it's really helpful.

Yesterday I found a mkv file to reproduce this problem on my macbook pro yesterday. So maybe this problem is not related to user's hardware/software environment.

I fix this problem by set hwdec to "auto" or "auto-copy". I don't know why, but it works.

**Comment by EdwardLiao** [comment]
Thanks for letting me know this method, it's really helpful.

Yesterday I found a mkv file to reproduce this problem on my macbook pro. So maybe this problem is not related to user's hardware/software environment.

I fix this problem by set hwdec to "auto" or "auto-copy". I don't know why, but it works.

**Comment by EdwardLiao** [comment]
Duplicated with #44
