### ISSUE TITLE
cannot work in windows 32bit

### ISSUE THREAD

**Issue by qilonelone** [Kagami/mpv.js#43]
Dear Kagami, when i pack with 'electron-packager' for windows 32bit, it just cannot work. tips 'Cannot load plug-ins'.  Curiously, it work in 64bit. what can I do.

**Comment by Kagami** [comment]
You need 32-bit mpv.dll for 32-bit electron package. How do you package mpv.dll?

**Comment by Kagami** [comment]
Also you would need 32-bit `mpvjs.node` because `prebuild-install` would install 64-bit binaries for 64-bit NodeJS. Might just extract it manually from `node_modules/mpv.js/prebuilds/mpv.js-v0.3.0-node-v42-win32-ia32.tar.gz` .

**Comment by Kagami** [comment]
Closing because problem seems to be straight-forward, please comment if it doesn't work for you.
