### ISSUE TITLE
Hardware Acceleration 

### ISSUE THREAD

**Issue by vsellen** [Kagami/mpv.js#45]
Hi Kagami,

I was able to use your plugin to with GPU acceleration by changing ```vo``` from ```opengl-cb``` to default and ```hwdec``` to various values. Full screen videos play much faster but are not rendered within the browser window. 

My goal is a full screen accelerated render of videos alternating with HTML content, so it would be nice if I could get this to work as a plugin rather than find a way to control the window that mpv creates. 

Is it the case that opengl-cb video output necessary for a ppapi plugin to render in the browser window?

I know this is outside the original purpose of your plugin, but do you have any advice in this area?

Thanks.

**Comment by Kagami** [comment]
Hi, if I understand you correctly you want hardware-accelerated decoding and there is already issue for that: #5. I haven't looked into it much, but wm4 (core developer of mpv) mentioned that it might be not that easy and require some work.

Closing in favor of #5, please correct me if you want something different.

**Comment by vsellen** [comment]
Not sure how I missed that. Thanks Kagami.
