### ISSUE TITLE
It works fine in Debug mode, but Release is incorrect in version!

### ISSUE THREAD

**Issue by oguzkulcu** [Kagami/mpv.js#46]
Hi, I'm using https://github.com/electron-react-boilerplate/electron-react-boilerplate. I included mpv.js in my project. I am using Debug mode without errors. But when I pack it, I get an error.

![Error](http://slazen.com/error.png)

My detection cannot load the mpv.js plugin.

The problem seems to be:

`const pluginDir = path.join (path.dirname (require.resolve ("mpv.js")), "build", "Release");`

**Comment by Kagami** [comment]
Could you upload the pack? Probably it misses the `mpvjs.node` file.

**Comment by oguzkulcu** [comment]
> Could you upload the pack? Probably it misses the `mpvjs.node` file.

![Error](http://slazen.com/mpverror.png)

I can compile mpvjs.node

**Comment by oguzkulcu** [comment]
app.asar successful including mpv.js. Despite getting the error.

**Comment by Kagami** [comment]
>app.asar successful including mpv.js

I think that's the problem, chromium can't load plugin from asar file (electron only [fixes Node/Web APIs](https://electronjs.org/docs/tutorial/application-packaging) to work with asar). Try passing `-c.asar=false` or `-c.asarUnpack='**/mpv.js/**/*'` to electron-builder.

**Comment by oguzkulcu** [comment]
@Kagami Unfortunately my problem is not solved :(. mpv.js is packaged successfully. But I still have problems.

I checked the file path in this code. Successfully accessible. But I still get the mistake.

`const pluginDir = path.join (path.dirname (require.resolve ("mpv.js")), "build", "Release");`

**Comment by Kagami** [comment]
Try to comment this line then: `if (process.platform !== "linux") {process.chdir(pluginDir);}`
Though this is strange. If you have this dir, you should be able to cd to it.

**Comment by oguzkulcu** [comment]
> Try to comment this line then: `if (process.platform !== "linux") {process.chdir(pluginDir);}`
> Though this is strange. If you have this dir, you should be able to cd to it.

Return:  `undefined`

**Comment by Kagami** [comment]
I mean delete this line and try to package&run again.

**Comment by oguzkulcu** [comment]
> I mean delete this line and try to package&run again.

Perfect, running. But again error:

![Error](http://slazen.com/pluginError.png)

**Comment by Kagami** [comment]
Do you have mpv installed? Does the [example](https://github.com/Kagami/mpv.js#example) work for you?

**Comment by oguzkulcu** [comment]
@Kagami https://github.com/Kagami/mpv.js/issues/14#issuecomment-353469238 
The suggestion here has solved my problem. After you pack the Electron application, you open the package and opened `mpv` folder into  `Resources/app/app`. I put `mpvjs.node` in it.

This code worked for me:
`const pluginDir = path.join(__dirname, 'mpv');`

Thank,you.

**Comment by Kagami** [comment]
I'm glad it works for you.
