### ISSUE TITLE
Build failed on windows X86_64

### ISSUE THREAD

**Issue by hakobianemil** [Kagami/mpv.js#48]
index.cc(9): fatal error C1083: Cannot open include file: 'GLES2/gl2.h': No such file or
 directory

**Comment by Kagami** [comment]
Have you setup NaCl SDK?
https://github.com/Kagami/mpv.js#build-on-x86

**Comment by hakobianemil** [comment]
Yes. I've downloaded nacl_sdk from https://github.com/Kagami/nacl_sdk/archive/master.zip not from https://developer.chrome.com/native-client/sdk/download. 
Now I'm getting en error **LINK : fatal error LNK1181: cannot open input file 'ppapi.lib'**

**Comment by Kagami** [comment]
You need to do all the steps from readme.
