### ISSUE TITLE
The plug-in cannot be loaded when electron uses the -- disable-gpu command

### ISSUE THREAD

**Issue by wuwei2150** [Kagami/mpv.js#50]
if (mpv_render_context_create(&mpv_gl_, mpv_, params) < 0)，crashed。
![无标题](https://user-images.githubusercontent.com/12472829/59764494-77108380-92ce-11e9-9851-1f2446b51865.png)

**Comment by Kagami** [comment]
This is correct behavior, OpenGL context is mandatory.
