### ISSUE TITLE
"Couldn't load plugin" on Ubuntu 16.04

### ISSUE THREAD

**Issue by weijian888** [Kagami/mpv.js#53]
I downloaded the git example, and run it.
But can't working on the ubuntu 16.04.
I installed the mpv using apt-get.And the mpv player can working successfully.
Please help me, I tryed it's OK on windows 10, but in ubuntu 16.04 is failture.

**Comment by TRPB** [comment]
On linux you need to run `gcc -Wl,--no-as-needed -shared -lavformat -o node_modules/electron` from the project directory.

**Comment by maximst** [comment]
@TRPB node_modules/electron is a directory, maybe you mean gcc -Wl,--no-as-needed -shared -lavformat -o node_modules/electron/mpvjs.node ?

**Comment by qwertyoldaccount** [comment]
> @TRPB node_modules/electron is a directory, maybe you mean gcc -Wl,--no-as-needed -shared -lavformat -o node_modules/electron/mpvjs.node ?

The correct path is `node_modules/electron/dist/libffmpeg.so`. The full command is the `use-system-ffmpeg` script in the [package.json](https://github.com/Kagami/mpv.js/blob/master/package.json) file.

**Comment by YzwOnO** [comment]
@weijian888  I encountered this problem in Ubuntu 18.04, but it has not been solved according to your plan. Is there any other solution.thanks
