### ISSUE TITLE
Mac: Couldn't load plugin after sign

### ISSUE THREAD

**Issue by dongjian** [Kagami/mpv.js#59]
Hello
env:
macOS Mojave 10.14.6
electron 4.2.12
I'm sure the mpv.js.node path is correct

I use electron-builder to package my app (without signing), and it's works fine
but if I package with signing , when open app it's show the err : Couldn't load plugin

**Comment by noamalffasy** [comment]
Hi @dongjian,
Were you able to solve it?

**Comment by pavladan** [comment]
I have the same problem. How to solve this?

**Comment by pavladan** [comment]
@noamalffasy, I solved this problem. This [comment](https://github.com/electron-userland/electron-builder/issues/3940#issuecomment-501702531 ) helped me.
