### ISSUE TITLE
Prerequisites for build on Windows

### ISSUE THREAD

**Issue by avrandrei** [Kagami/mpv.js#7]
Hi,

This seems like a very nice approach for supporting all these video file formats in electron apps.

Are there any prerequisites for the build to work on Windows? Any SDKs that I should install first, and build after?

I don't really have any experience with plugins and how they integrate with electron

**Comment by Kagami** [comment]
Hi. I'm going to publish prebuild binaries and build instructions soon.

**Comment by avrandrei** [comment]
That's awesome! 
Looking forward to it!

Thanks a lot.

**Comment by avrandrei** [comment]
I've installed the Native Client sdk and picked the libmpv files and placed them at the path found in the bindings.gyp.

All dependencies are found, but I get the following linking error:
LINK : fatal error LNK1181: cannot open input file 'ppapi.lib'

Is there anything else I need to do in order to have a successful build?

**Comment by Kagami** [comment]
Are you using 64bit OS?

**Comment by avrandrei** [comment]
Yes. I'm on a 64bit Win 8.1 machine

**Comment by Kagami** [comment]
You need to compile 64bit host NaCl binaries.

1. Open `C:\nacl_sdk\pepper49\tools\host_vc.mk` and replace `x86_32` with `x86_64`
2. Open cmd, cd to `C:\nacl_sdk\pepper49\src`, run `vcvars.bat`
3. Run `make TOOLCHAIN=win`

It should create directory `C:\nacl_sdk\pepper49\lib\win_x86_64_host\Release`.

**Comment by Kagami** [comment]
Added build instructions. Let me know if it works for you.

**Comment by avrandrei** [comment]
Yaay, thank you!

I managed to build it and run the example. One thing's not very clear for me. 

Why copy libmpv to the System32 folder?

How is this going to affect packaging the app for usage with a windows installer?

**Comment by Kagami** [comment]
Just put `mpv-1.dll` to the same directory as `mpvjs.node`.
This readme section is for local use, I will try to make it more clear and add info regarding shipping.

**Comment by Kagami** [comment]
Please try `0.2.0` release. Should work without compilation.

**Comment by avrandrei** [comment]
I have just tried v. 0.2.0 and it works in Windows without compilation
Thanks a lot!
