### ISSUE TITLE
Pepper is deprecated

### ISSUE THREAD

**Issue by Dartandr** [Kagami/mpv.js#81]
SSL Certificate appears to be dead, how do I set up the buildenv in that case?
![image](https://user-images.githubusercontent.com/32641958/105375560-dd335a00-5c19-11eb-8681-f99d825104f3.png)

**Comment by Kagami** [comment]
https://github.com/Kagami/nacl_sdk try this one

**Comment by Dartandr** [comment]
still ssl related but different error 
![image](https://user-images.githubusercontent.com/32641958/105379618-1241ab80-5c1e-11eb-9cbf-cb9e2128f1eb.png)

**Comment by Dartandr** [comment]
I got it working on a different machine
