### ISSUE TITLE
Test relative plugin paths on Windows

### ISSUE THREAD

**Issue by Kagami** [Kagami/mpv.js#9]
See https://github.com/Kagami/mpv.js/commit/f7ef2dc53aea1c13ef7744f7df8d4550ea32bc0f.

**Comment by Kagami** [comment]
Very strange.

* `process.chdir("node_modules/electron")` works
* `process.chdir("node_modules/electron/dist")` works
* `process.chdir("node_modules")` **doesn't work**
* `process.chdir("node_modules/write")` works

I guess it might be another bug in `pepper_plugin_list.cc`. @romaincointepas do you see the same? (With line 40 commented.)

**Comment by romaincointepas** [comment]
@Kagami Did not test with `mpv.js` specifically, but I'm seeing the same behavior. I can't figure out why either (I'm wondering if the problem is with `process.chdir()` not liking the first part of the path, or `--register-pepper-plugins` not liking the second part).

**Comment by Kagami** [comment]
Surely `process.chdir` is fine, it's pepper path parsing.
I guess it's better to keep the current logic then.
